### PR TITLE
Replace mockapi with auth-json-server

### PR DESCRIPTION
**Pull request by eliangcs**
We've set up https://auth-json-server.zapier.ninja, providing all kinds of fake endpoints and authentications for testing. Let's use it for our example apps.

### CODE REVIEW

**Review by xavdid — APPROVED** [review]
sweet! looks super useful. Easy to use. Are similar PRs for the other apps coming?

**Comment by eliangcs** [comment]
@xavdid yep, will slowly move other apps, too!

**Comment by FokkeZB** [comment]
@eliangcs does this mean we move away from using https://github.com/zapier/oauth-test-endpoints? If so, we can spin that Lambda down (and archive the repo).

**Comment by eliangcs** [comment]
@FokkeZB yes, I think so. `oauth-test-endpoints` doesn't provide resource endpoints and other auths, so I figure it's easier to just have one server for auths and resources. But let's not bring it down yet until we move all the apps.

**Pull request merged**
